param(
  [string]$Doc = "docs\architecture\aetra-economics-spec.md",
  [string]$Policy = "app\params\aetra_economics_spec.go",
  [string]$Tests = "app\params\aetra_economics_spec_test.go",
  [string]$ModuleTypes = "x\aetra-economics\types\state.go",
  [string]$ModuleTypesTests = "x\aetra-economics\types\state_test.go",
  [string]$ModuleKeeperTests = "x\aetra-economics\keeper\keeper_test.go"
)

$ErrorActionPreference = "Stop"

$RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))

function Resolve-RepoPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
  return Join-Path $RepoRoot $Path
}

function Assert-Contains {
  param([string]$Text, [string]$Pattern, [string]$Message)
  if ($Text -notmatch $Pattern) { throw $Message }
}

$docText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Doc)
$policyText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Policy)
$testText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Tests)
$moduleTypesText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $ModuleTypes)
$moduleTypesTestText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $ModuleTypesTests)
$moduleKeeperTestText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $ModuleKeeperTests)

foreach ($term in @(
    'x/aetra-economics Module Specification',
    'Purpose: low/moderate inflation, fee burn, treasury allocation, reward smoothing, and transparent APR model.',
    'economic-control module of Aetra',
    'implement low/moderate inflation',
    'implement fee burn',
    'implement treasury allocation',
    'implement reward smoothing',
    'expose a transparent APR model',
    'The implementation gate is `app/params/aetra_economics_spec.go`',
    '`AetraEconomicsModuleName` must be `x/aetra-economics`',
    'wrong or missing module identity must fail validation',
    '23.1 Responsibilities',
    'calculate dynamic inflation',
    'track bonded ratio',
    'estimate staking APR',
    'split fees',
    'burn configured fee share',
    'send configured share to distribution/rewards',
    'send configured share to treasury',
    'smooth reward changes',
    'expose economic metrics',
    'protect supply invariants',
    'BuildAetraEconomicsResponsibilitiesReport',
    '23.2 State',
    'Params:',
    'InflationMinBps',
    'InflationMaxBps',
    'InflationChangeRateBps',
    'TargetBondedRatioBps',
    'BurnFeeShareBps',
    'RewardFeeShareBps',
    'TreasuryFeeShareBps',
    'RewardSmoothingEpochs',
    'AprTargetMinBps',
    'AprTargetMaxBps',
    'EpochEconomics:',
    'EpochNumber',
    'StartHeight',
    'EndHeight',
    'BondedRatioBps',
    'InflationBps',
    'EstimatedAprBps',
    'FeesCollected',
    'FeesBurned',
    'FeesToRewards',
    'FeesToTreasury',
    'MintedRewards',
    'SupplyStats:',
    'TotalMinted',
    'TotalBurned',
    'NetIssuance',
    'BuildAetraEconomicsStateSpecReport',
    '23.3 Inflation curve',
    'if bonded_ratio < target:',
    'increase inflation gradually',
    'if bonded_ratio > target:',
    'decrease inflation gradually',
    'inflation never below min',
    'inflation never above max',
    'inflation change per epoch bounded',
    'no floating point',
    'no per-block instability',
    'all calculations deterministic',
    'BuildAetraEconomicsInflationCurveReport',
    'ComputeInflationBps',
    'ComputeNextInflationBps',
    'InflationChangeRateBps',
    'ApplyEpoch',
    '23.4 Fee split rules',
    'Fee split must always sum to 100%.',
    'BurnFeeShareBps: 3000-6000',
    'RewardFeeShareBps: 2000-4000',
    'TreasuryFeeShareBps: 1000-2000',
    '50% burn',
    '35% validators/delegators',
    '15% treasury',
    'sum != 10000 bps',
    'any share is negative',
    'burn share exceeds max governance bound',
    'treasury share exceeds max governance bound',
    'rewards share is zero unless explicitly permitted by emergency governance',
    'BuildAetraEconomicsFeeSplitRulesReport',
    'ComputeFeeSplit',
    'QueryFeeSplitParams',
    '23.5 APR query',
    'inflation-only APR',
    'fee-adjusted APR',
    'validator commission impact',
    'estimated delegator APR',
    'estimated validator gross APR',
    'estimated validator net APR',
    'APR must be labeled as estimate, not guaranteed return.',
    'BuildAetraEconomicsAPRQueryReport',
    'EstimateAPRBreakdown',
    'QueryEstimatedAPR',
    '23.6 Tests',
    'inflation increases when bonded ratio below target',
    'inflation decreases when bonded ratio above target',
    'inflation remains within min/max',
    'inflation change rate bounded',
    'fee split exact accounting',
    'burn accounting',
    'treasury accounting',
    'rewards accounting',
    'APR estimate math',
    'zero-fee block handling',
    'high-fee block handling',
    'export/import economics state',
    'supply invariant after many epochs',
    'governance invalid params rejected',
    'BuildAetraEconomicsTestingRequirementsReport'
  )) {
  Assert-Contains -Text $docText -Pattern ([regex]::Escape($term)) -Message "aetra economics spec doc missing: $term"
}

foreach ($term in @(
    'AetraEconomicsModuleName',
    'AetraEconomicsSpecEvidence',
    'AetraEconomicsSpecReport',
    'DefaultAetraEconomicsSpecEvidence',
    'ValidateAetraEconomicsSpec',
    'BuildAetraEconomicsSpecReport',
    'AetraEconomicsPurposeLowModerateInflation',
    'AetraEconomicsPurposeFeeBurn',
    'AetraEconomicsPurposeTreasuryAllocation',
    'AetraEconomicsPurposeRewardSmoothing',
    'AetraEconomicsPurposeTransparentAPRModel',
    'AetraEconomicsResponsibilitiesEvidence',
    'AetraEconomicsResponsibilitiesReport',
    'DefaultAetraEconomicsResponsibilitiesEvidence',
    'ValidateAetraEconomicsResponsibilities',
    'BuildAetraEconomicsResponsibilitiesReport',
    'AetraEconomicsResponsibilityDynamicInflation',
    'AetraEconomicsResponsibilityBondedRatio',
    'AetraEconomicsResponsibilityStakingAPR',
    'AetraEconomicsResponsibilityFeeSplit',
    'AetraEconomicsResponsibilityBurnFeeShare',
    'AetraEconomicsResponsibilityRewardsShare',
    'AetraEconomicsResponsibilityTreasuryShare',
    'AetraEconomicsResponsibilityRewardSmoothing',
    'AetraEconomicsResponsibilityEconomicMetrics',
    'AetraEconomicsResponsibilitySupplyInvariants',
    'AetraEconomicsStateSpecEvidence',
    'AetraEconomicsStateSpecReport',
    'DefaultAetraEconomicsStateSpecEvidence',
    'ValidateAetraEconomicsStateSpec',
    'BuildAetraEconomicsStateSpecReport',
    'AetraEconomicsStateParams',
    'AetraEconomicsStateEpochEconomics',
    'AetraEconomicsStateSupplyStats',
    'AetraEconomicsStateParamInflationMinBps',
    'AetraEconomicsStateParamInflationMaxBps',
    'AetraEconomicsStateParamInflationChangeRateBps',
    'AetraEconomicsStateParamTargetBondedRatioBps',
    'AetraEconomicsStateParamBurnFeeShareBps',
    'AetraEconomicsStateParamRewardFeeShareBps',
    'AetraEconomicsStateParamTreasuryFeeShareBps',
    'AetraEconomicsStateParamRewardSmoothingEpochs',
    'AetraEconomicsStateParamAprTargetMinBps',
    'AetraEconomicsStateParamAprTargetMaxBps',
    'AetraEconomicsStateEpochNumber',
    'AetraEconomicsStateEpochStartHeight',
    'AetraEconomicsStateEpochEndHeight',
    'AetraEconomicsStateEpochBondedRatioBps',
    'AetraEconomicsStateEpochInflationBps',
    'AetraEconomicsStateEpochEstimatedAprBps',
    'AetraEconomicsStateEpochFeesCollected',
    'AetraEconomicsStateEpochFeesBurned',
    'AetraEconomicsStateEpochFeesToRewards',
    'AetraEconomicsStateEpochFeesToTreasury',
    'AetraEconomicsStateEpochMintedRewards',
    'AetraEconomicsStateSupplyTotalMinted',
    'AetraEconomicsStateSupplyTotalBurned',
    'AetraEconomicsStateSupplyNetIssuance',
    'AetraEconomicsInflationCurveEvidence',
    'AetraEconomicsInflationCurveReport',
    'DefaultAetraEconomicsInflationCurveEvidence',
    'ValidateAetraEconomicsInflationCurve',
    'BuildAetraEconomicsInflationCurveReport',
    'AetraEconomicsInflationCurveBelowTargetIncreases',
    'AetraEconomicsInflationCurveAboveTargetDecreases',
    'AetraEconomicsInflationCurveNeverBelowMin',
    'AetraEconomicsInflationCurveNeverAboveMax',
    'AetraEconomicsInflationCurveEpochChangeBounded',
    'AetraEconomicsInflationCurveNoFloatingPoint',
    'AetraEconomicsInflationCurveNoPerBlockInstability',
    'AetraEconomicsInflationCurveDeterministic',
    'AetraEconomicsFeeSplitRulesEvidence',
    'AetraEconomicsFeeSplitRulesReport',
    'DefaultAetraEconomicsFeeSplitRulesEvidence',
    'ValidateAetraEconomicsFeeSplitRules',
    'BuildAetraEconomicsFeeSplitRulesReport',
    'AetraEconomicsFeeSplitSumToBasisPoints',
    'AetraEconomicsFeeSplitRecommendedBurnRange',
    'AetraEconomicsFeeSplitRecommendedRewardRange',
    'AetraEconomicsFeeSplitRecommendedTreasuryRange',
    'AetraEconomicsFeeSplitRejectsInvalidSum',
    'AetraEconomicsFeeSplitRejectsNegativeShares',
    'AetraEconomicsFeeSplitRejectsBurnAboveGovernanceMax',
    'AetraEconomicsFeeSplitRejectsTreasuryAboveMax',
    'AetraEconomicsFeeSplitRejectsZeroRewards',
    'AetraEconomicsAPRQueryEvidence',
    'AetraEconomicsAPRQueryReport',
    'DefaultAetraEconomicsAPRQueryEvidence',
    'ValidateAetraEconomicsAPRQuery',
    'BuildAetraEconomicsAPRQueryReport',
    'AetraEconomicsAPRQueryInflationOnly',
    'AetraEconomicsAPRQueryFeeAdjusted',
    'AetraEconomicsAPRQueryCommissionImpact',
    'AetraEconomicsAPRQueryDelegatorEstimate',
    'AetraEconomicsAPRQueryValidatorGross',
    'AetraEconomicsAPRQueryValidatorNet',
    'AetraEconomicsAPRQueryLabeledAsEstimate',
    'AetraEconomicsTestingRequirementsEvidence',
    'AetraEconomicsTestingRequirementsReport',
    'DefaultAetraEconomicsTestingRequirementsEvidence',
    'ValidateAetraEconomicsTestingRequirements',
    'BuildAetraEconomicsTestingRequirementsReport',
    'AetraEconomicsRequiredTestInflationBelowTarget',
    'AetraEconomicsRequiredTestInflationAboveTarget',
    'AetraEconomicsRequiredTestInflationMinMax',
    'AetraEconomicsRequiredTestInflationChangeBounded',
    'AetraEconomicsRequiredTestFeeSplitAccounting',
    'AetraEconomicsRequiredTestBurnAccounting',
    'AetraEconomicsRequiredTestTreasuryAccounting',
    'AetraEconomicsRequiredTestRewardsAccounting',
    'AetraEconomicsRequiredTestAPRMath',
    'AetraEconomicsRequiredTestZeroFeeBlock',
    'AetraEconomicsRequiredTestHighFeeBlock',
    'AetraEconomicsRequiredTestExportImportState',
    'AetraEconomicsRequiredTestSupplyInvariantManyEpochs',
    'AetraEconomicsRequiredTestGovernanceInvalidParams'
  )) {
  Assert-Contains -Text $policyText -Pattern ([regex]::Escape($term)) -Message "aetra economics spec policy missing: $term"
}

foreach ($term in @(
    'TestDefaultAetraEconomicsSpecCoversModulePurpose',
    'TestAetraEconomicsSpecRejectsMissingPurposeComponents',
    'TestAetraEconomicsSpecRejectsWrongModuleIdentity',
    'TestDefaultAetraEconomicsResponsibilitiesCoverSection231',
    'TestAetraEconomicsResponsibilitiesRejectMissingRequiredItems',
    'TestDefaultAetraEconomicsStateSpecCoversSection232',
    'TestAetraEconomicsStateSpecRejectsMissingFields',
    'TestAetraEconomicsStateSpecRejectsDuplicateUnexpectedAndWrongModule',
    'TestDefaultAetraEconomicsInflationCurveCoversSection233',
    'TestAetraEconomicsInflationCurveRejectsMissingRequiredItems',
    'TestDefaultAetraEconomicsFeeSplitRulesCoverSection234',
    'TestAetraEconomicsFeeSplitRulesRejectMissingRequiredItems',
    'TestDefaultAetraEconomicsAPRQueryCoversSection235',
    'TestAetraEconomicsAPRQueryRejectsMissingRequiredItems',
    'TestDefaultAetraEconomicsTestingRequirementsCoverSection236',
    'TestAetraEconomicsTestingRequirementsRejectMissingRequiredItems'
  )) {
  Assert-Contains -Text $testText -Pattern ([regex]::Escape($term)) -Message "aetra economics spec tests missing: $term"
}

foreach ($term in @(
    'InflationChangeRateBps',
    'ComputeInflationBps',
    'ComputeNextInflationBps',
    'ApplyEpoch',
    'state.CurrentInflationBps',
    'BurnMinBps',
    'BurnMaxBps',
    'BurnCurrentBps',
    'ValidatorRewardMinBps',
    'ValidatorRewardMaxBps',
    'ValidatorRewardBps',
    'TreasuryMinBps',
    'TreasuryMaxBps',
    'TreasuryBps',
    'EmergencyAllowZeroRewardShare',
    'ComputeFeeSplit',
    'QueryEstimatedAPRResponse',
    'IsEstimate',
    'EstimateLabel',
    'InflationOnlyAPRBps',
    'FeeAdjustedAPRBps',
    'ValidatorCommissionImpactBps',
    'EstimatedDelegatorAPRBps',
    'EstimatedValidatorGrossAPRBps',
    'EstimatedValidatorNetAPRBps',
    'EstimateAPRBreakdown'
  )) {
  Assert-Contains -Text $moduleTypesText -Pattern ([regex]::Escape($term)) -Message "aetra economics module types missing: $term"
}

foreach ($term in @(
    'TestInflationCurveRespondsToBondedRatio',
    'TestBoundedInflation',
    'TestInflationChangePerEpochIsBounded',
    'TestApplyEpochUsesBoundedInflationStep',
    'TestFeeSplitAccounting',
    'TestFeeSplitParamsRejectUnsafeRules',
    'TestAPRBreakdownLabelsEstimateAndCommissionImpact',
    'TestZeroFeeBlockHandling',
    'TestHighFeeBlockHandling',
    'TestSupplyInvariantAfterManyEpochs'
  )) {
  Assert-Contains -Text $moduleTypesTestText -Pattern ([regex]::Escape($term)) -Message "aetra economics module tests missing: $term"
}

foreach ($term in @(
    'TestKeeperExportImportPreservesEconomicsState',
    'TestGovernanceInvalidParamsRejected',
    'QueryEstimatedAPR'
  )) {
  Assert-Contains -Text $moduleKeeperTestText -Pattern ([regex]::Escape($term)) -Message "aetra economics keeper tests missing: $term"
}

Write-Host "aetra economics spec doc test passed"
